require("bufferline").setup {}

--vim.api.nvim_set_hl(0, 'BufferLineFill', { bg = 'NONE' })
--vim.api.nvim_set_hl(0, 'BufferLineBackground', { bg = 'NONE' })
--vim.api.nvim_set_hl(0, 'BufferLineBufferVisible', { bg = 'NONE' })
--vim.api.nvim_set_hl(0, 'BufferLineBufferSelected', { bg = 'NONE' })
--vim.api.nvim_set_hl(0, 'BufferLineSeparator', { bg = 'NONE' })
--vim.api.nvim_set_hl(0, 'BufferLineSeparatorSelected', { bg = 'NONE' })
--vim.api.nvim_set_hl(0, 'BufferLineSeparatorVisible', { bg = 'NONE' })
--vim.api.nvim_set_hl(0, 'BufferLineModified', { bg = 'NONE' })
--vim.api.nvim_set_hl(0, 'BufferLineModifiedSelected', { bg = 'NONE' })
--vim.api.nvim_set_hl(0, 'BufferLineModifiedVisible', { bg = 'NONE' })
--vim.api.nvim_set_hl(0, 'BufferLineCloseButton', { bg = 'NONE' })
--vim.api.nvim_set_hl(0, 'BufferLineCloseButtonVisible', { bg = 'NONE' })
--vim.api.nvim_set_hl(0, 'BufferLineCloseButtonSelected', { bg = 'NONE' })
--vim.api.nvim_set_hl(0, 'BufferLineIndicatorSelected', { bg = 'NONE' })
--vim.api.nvim_set_hl(0, 'BufferLineIcon', { bg = 'NONE' })
--vim.api.nvim_set_hl(0, 'BufferLineIconVisible', { bg = 'NONE' })
--vim.api.nvim_set_hl(0, 'BufferLineIconSelected', { bg = 'NONE' })
